from Replication import *
import sys

genome_test = "CATGGGTATCGATACTACCACCAACATCATACACCGACCACACACACACCGACCACACCCACACACACACTACCACCACACACACACCACACCACACACACCACACCAC"


# Prints Results

if __name__ == "__main__":
    genome_sample = "CATGGGTATCGATACTACCACCAACATCATACACCGACCACACACACACCGACCACACCCACACACACACTACCACCACACACACACCACACCACACACACCACACCAC"
    
    print("1. Skew Array:", SkewArray(genome_sample[:20]))
    print("2. Minimum Skew:", MinimumSkew("TAAAGACTGCCGAGAGGCCAACACGAGTGCTAGAACGAGTATTCCCAATCTCCACGCATAGGCACTCTACACTACACCTCAACTCCACACTCTA"))
    print("3. Hamming Distance:", HammingDistance("GGGCGACACTCC", "GGGACTACCCGT"))
    print("4. Approximate Pattern Matching:", ApproximatePatternMatching("CGCCCGAATCCAGAACGCATTCCCATATTTCGGGACCACTGGCCTCCACGGTACGGACGTCAATCAAAT", "ATTCTGGA", 3))
    print("5. Approximate Pattern Count:", ApproximatePatternCount("AAAAA", "AACAAGCTGATAAACACTCACTACTACCAACTACCAACTACCAACACCAACTACCAACCCACACACACACACCACACACACCAC", 2))
    print("6. Faster Symbol Array:", FasterSymbolArray("AAAAGGGG", "A"))